#Application name
spring.application.name=demo
#PostgreSQL database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/placement_db
spring.datasource.username=postgres
spring.datasource.password=676369
#JPS settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#server port
server.port=8080
